$axure.loadCurrentPage({
  "url":"新闻列表页_-_1.html",
  "generationDate":new Date(1385788193545.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b1b036d630d640b59a65852427b04cd0",
    "type":"Axure:Page",
    "name":"新闻列表页 - 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fcfa3cf2cb304530b67011a734d9d0d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":250,
              "y":162},
            "size":{
              "width":40,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7db2d4e6c98446e88501dc2e62c4a139",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":250,
                  "y":162},
                "size":{
                  "width":40,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/精品课程-_列表页_-_1/u0.png"}},
{
          "id":"e5276a1a20ea4efba7d6ba5366941430",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":700,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34801031f92048d9a114cc90cb8f76e0",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":700,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c80b7220f88d44edabab3c131e8f1308",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef55be2ea5f04ca9a3a13ce654693dfe",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页_-_1/u2.png"}},
{
                  "id":"c2a3b428c9534c1b8d205c8eeaaf4916",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ddf4f2a1960f4338a40a6bf3e362b009",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页_-_1/u2.png"}},
{
                  "id":"14f066ee67f046a1b32b75f9e26e4f43",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24f900f0c40b45698676ceecbd62b8c9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页_-_1/u2.png"}},
{
                  "id":"7d8ee01c2f914251a44ff56d23bb8702",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4202155149bc488aa0453f48d3470dfb",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页_-_1/u2.png"}},
{
                  "id":"0dcd4025bd134b4abaa8550e4711e441",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33b46947030641e7b726f66fad478c9f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页_-_1/u2.png"}},
{
                  "id":"8e0be7d8b4c44ed1ad55d606655b3e19",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bd16f67250dd4ab4a8e9c386bcd43610",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页_-_1/u2.png"}},
{
                  "id":"8ec7481cd146421cad8d84b5fe9ffda2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":600,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"60e6f5344d6544979311cdf2e363a977",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":600,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻列表页_-_1/u16.png"}}]}]},
{
          "id":"188fe3891201463391a1932e88655d9c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":10},
            "size":{
              "width":700,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a44af009bab24b83b73e0d0b8ddddf3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":10},
                "size":{
                  "width":700,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_-_1/u16.png"}},
{
          "id":"21ca69cbed044161976aedfb01f3fa3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":24},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c8d377c2b5d4e6599e0051720fc92f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":648,
                  "y":24},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c5e6d1d54dc49da9f5a798e247a4d6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":711,
              "y":24},
            "size":{
              "width":27,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4268fef97c4b42fb9c8e43f9f7c6f2bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":711,
                  "y":24},
                "size":{
                  "width":27,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44e7c9f9714646f2aeaa0fbf8f6d3070",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":14},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bddcba9c1e6c47e49fb486ffa98d8c5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":14},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_-_1/u22.png"}},
{
          "id":"a63b4754012b43e0b3872ade1eb9f45c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":21},
            "size":{
              "width":25,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a0db3a3997a443ba5017b6a29b9afd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":21},
                "size":{
                  "width":25,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6306a876d61421983f9831182cd1973",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":80},
            "size":{
              "width":700,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3e9a8b3006d493e8c747e487bcf793c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":80},
                "size":{
                  "width":700,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_-_1/u26.png"}},
{
          "id":"0e5bfdc0f3924dd3aad7b69827040464",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":68,
              "y":87},
            "size":{
              "width":103,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1142b3ad7aaa42c292080fd3d799ec80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":68,
                  "y":87},
                "size":{
                  "width":103,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"887f22df4f9f46de99dcb631880bb384",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":560},
            "size":{
              "width":702,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b65355290b54ae5b32c9dc77e68cf39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":560},
                "size":{
                  "width":702,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_-_1/u320.png"}},
{
          "id":"87038de4baa1488d826eb17a751dd4a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":120},
            "size":{
              "width":700,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4301070b45f44f35965f19cebefaadc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":120},
                "size":{
                  "width":700,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表页_-_1/u34.png"}},
{
          "id":"813756243bcf4b3eab830beb599000f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":213,
              "y":501},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0219c81fbba451bb8cbbf770e17c856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":213,
                  "y":501},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5daa8b5220c94fd08eedef2d86af5598",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":501},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d741089a97c340a8b6b77d28ed895d1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":501},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"666899a1faf04f16ad4bd9c6e72c85d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":323,
              "y":501},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c73e15f5ed4d0cb69105b49684ef03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323,
                  "y":501},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5584070d5d424298993b02d833ff938a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":501},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"713dd6dc3ce14305b0ef8c4f8322660d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":501},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed664b2d142747b0a688d59f116d3287",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":463,
              "y":501},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca2d0ba9d5e8493ab426e7d19ce67eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":463,
                  "y":501},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6867e96f8ca4381ac7052f64378233d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":162},
            "size":{
              "width":611,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/教师介绍_-_详情页_-_1/u135_line.png"}},
{
          "id":"285c19f63d574a149ad1e521649665e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":83,
              "y":150},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dce90ac6692b443a9c1e108ac39122eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":83,
                  "y":150},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21470cf8af904d9481eab49690e24c47",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":225},
            "size":{
              "width":611,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1385f9bcfea488ebef393ef6a4310b2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC'",
                "fontWeight":"200",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":372,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2e711be2571446cb9cd1f410ae25c44c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'STHeitiSC-Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":372,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新闻列表页_-_1/u50.png"}},
{
              "id":"6fd72278a3b840419f60ac177cfb964f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":372,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74c91e6f308a4b28a36a8784c65c1ce3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":372,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新闻列表页_-_1/u54.png"}},
{
              "id":"d0d83e8d00e64260b8024bdde371f622",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":372,
                  "height":25}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6030266b2a3941e7880902351d990308",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":372,
                      "height":25}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新闻列表页_-_1/u58.png"}},
{
              "id":"749a4b01166945c98dde9e9d2f7dace8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":0},
                "size":{
                  "width":239,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f969a42b3a1c4c66b2650b876d2b5900",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":0},
                    "size":{
                      "width":239,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新闻列表页_-_1/u52.png"}},
{
              "id":"a9b099962f1d4ed2be1332ceec4476a4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":20},
                "size":{
                  "width":239,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"041486e4714149f99e8dbdf00c593731",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":20},
                    "size":{
                      "width":239,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新闻列表页_-_1/u52.png"}},
{
              "id":"fcb2b94906f744d2b7c78d9bb91c05d2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":40},
                "size":{
                  "width":239,
                  "height":25}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4bd24607cc64e7ba7db7210fa5e2eee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":40},
                    "size":{
                      "width":239,
                      "height":25}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新闻列表页_-_1/u60.png"}},
{
              "id":"fa22cd05f0344423b2b77663cc831c7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":65},
                "size":{
                  "width":372,
                  "height":25}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4db789a54ea045729d39170828da77c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":65},
                    "size":{
                      "width":372,
                      "height":25}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新闻列表页_-_1/u58.png"}},
{
              "id":"ae84eca50ce84e5e974bdee4acac1198",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":65},
                "size":{
                  "width":239,
                  "height":25}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5883dd3b170b4f7695b9cf40916c445e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":65},
                    "size":{
                      "width":239,
                      "height":25}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新闻列表页_-_1/u60.png"}},
{
              "id":"e346e05e65554e9a822796c5042b8efe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":372,
                  "height":25}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"adabf8b60e7a446588d93cb9b9b558e1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":372,
                      "height":25}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新闻列表页_-_1/u66.png"}},
{
              "id":"3c9ec90ff6c7437694e8d35fea33bfd0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":90},
                "size":{
                  "width":239,
                  "height":25}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bde0c56773be4561a81d2d170819d1a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":90},
                    "size":{
                      "width":239,
                      "height":25}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新闻列表页_-_1/u68.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "fcfa3cf2cb304530b67011a734d9d0d4":{
      "scriptId":"u0"},
    "7db2d4e6c98446e88501dc2e62c4a139":{
      "scriptId":"u1"},
    "e5276a1a20ea4efba7d6ba5366941430":{
      "scriptId":"u2"},
    "34801031f92048d9a114cc90cb8f76e0":{
      "scriptId":"u3"},
    "c80b7220f88d44edabab3c131e8f1308":{
      "scriptId":"u4"},
    "ef55be2ea5f04ca9a3a13ce654693dfe":{
      "scriptId":"u5"},
    "c2a3b428c9534c1b8d205c8eeaaf4916":{
      "scriptId":"u6"},
    "ddf4f2a1960f4338a40a6bf3e362b009":{
      "scriptId":"u7"},
    "14f066ee67f046a1b32b75f9e26e4f43":{
      "scriptId":"u8"},
    "24f900f0c40b45698676ceecbd62b8c9":{
      "scriptId":"u9"},
    "7d8ee01c2f914251a44ff56d23bb8702":{
      "scriptId":"u10"},
    "4202155149bc488aa0453f48d3470dfb":{
      "scriptId":"u11"},
    "0dcd4025bd134b4abaa8550e4711e441":{
      "scriptId":"u12"},
    "33b46947030641e7b726f66fad478c9f":{
      "scriptId":"u13"},
    "8e0be7d8b4c44ed1ad55d606655b3e19":{
      "scriptId":"u14"},
    "bd16f67250dd4ab4a8e9c386bcd43610":{
      "scriptId":"u15"},
    "8ec7481cd146421cad8d84b5fe9ffda2":{
      "scriptId":"u16"},
    "60e6f5344d6544979311cdf2e363a977":{
      "scriptId":"u17"},
    "188fe3891201463391a1932e88655d9c":{
      "scriptId":"u18"},
    "a44af009bab24b83b73e0d0b8ddddf3f":{
      "scriptId":"u19"},
    "21ca69cbed044161976aedfb01f3fa3f":{
      "scriptId":"u20"},
    "2c8d377c2b5d4e6599e0051720fc92f3":{
      "scriptId":"u21"},
    "9c5e6d1d54dc49da9f5a798e247a4d6e":{
      "scriptId":"u22"},
    "4268fef97c4b42fb9c8e43f9f7c6f2bb":{
      "scriptId":"u23"},
    "44e7c9f9714646f2aeaa0fbf8f6d3070":{
      "scriptId":"u24"},
    "bddcba9c1e6c47e49fb486ffa98d8c5b":{
      "scriptId":"u25"},
    "a63b4754012b43e0b3872ade1eb9f45c":{
      "scriptId":"u26"},
    "6a0db3a3997a443ba5017b6a29b9afd3":{
      "scriptId":"u27"},
    "b6306a876d61421983f9831182cd1973":{
      "scriptId":"u28"},
    "c3e9a8b3006d493e8c747e487bcf793c":{
      "scriptId":"u29"},
    "0e5bfdc0f3924dd3aad7b69827040464":{
      "scriptId":"u30"},
    "1142b3ad7aaa42c292080fd3d799ec80":{
      "scriptId":"u31"},
    "887f22df4f9f46de99dcb631880bb384":{
      "scriptId":"u32"},
    "1b65355290b54ae5b32c9dc77e68cf39":{
      "scriptId":"u33"},
    "87038de4baa1488d826eb17a751dd4a0":{
      "scriptId":"u34"},
    "4301070b45f44f35965f19cebefaadc9":{
      "scriptId":"u35"},
    "813756243bcf4b3eab830beb599000f7":{
      "scriptId":"u36"},
    "d0219c81fbba451bb8cbbf770e17c856":{
      "scriptId":"u37"},
    "5daa8b5220c94fd08eedef2d86af5598":{
      "scriptId":"u38"},
    "d741089a97c340a8b6b77d28ed895d1a":{
      "scriptId":"u39"},
    "666899a1faf04f16ad4bd9c6e72c85d8":{
      "scriptId":"u40"},
    "69c73e15f5ed4d0cb69105b49684ef03":{
      "scriptId":"u41"},
    "5584070d5d424298993b02d833ff938a":{
      "scriptId":"u42"},
    "713dd6dc3ce14305b0ef8c4f8322660d":{
      "scriptId":"u43"},
    "ed664b2d142747b0a688d59f116d3287":{
      "scriptId":"u44"},
    "ca2d0ba9d5e8493ab426e7d19ce67eda":{
      "scriptId":"u45"},
    "b6867e96f8ca4381ac7052f64378233d":{
      "scriptId":"u46"},
    "285c19f63d574a149ad1e521649665e4":{
      "scriptId":"u47"},
    "dce90ac6692b443a9c1e108ac39122eb":{
      "scriptId":"u48"},
    "21470cf8af904d9481eab49690e24c47":{
      "scriptId":"u49"},
    "f1385f9bcfea488ebef393ef6a4310b2":{
      "scriptId":"u50"},
    "2e711be2571446cb9cd1f410ae25c44c":{
      "scriptId":"u51"},
    "749a4b01166945c98dde9e9d2f7dace8":{
      "scriptId":"u52"},
    "f969a42b3a1c4c66b2650b876d2b5900":{
      "scriptId":"u53"},
    "6fd72278a3b840419f60ac177cfb964f":{
      "scriptId":"u54"},
    "74c91e6f308a4b28a36a8784c65c1ce3":{
      "scriptId":"u55"},
    "a9b099962f1d4ed2be1332ceec4476a4":{
      "scriptId":"u56"},
    "041486e4714149f99e8dbdf00c593731":{
      "scriptId":"u57"},
    "d0d83e8d00e64260b8024bdde371f622":{
      "scriptId":"u58"},
    "6030266b2a3941e7880902351d990308":{
      "scriptId":"u59"},
    "fcb2b94906f744d2b7c78d9bb91c05d2":{
      "scriptId":"u60"},
    "a4bd24607cc64e7ba7db7210fa5e2eee":{
      "scriptId":"u61"},
    "fa22cd05f0344423b2b77663cc831c7b":{
      "scriptId":"u62"},
    "4db789a54ea045729d39170828da77c5":{
      "scriptId":"u63"},
    "ae84eca50ce84e5e974bdee4acac1198":{
      "scriptId":"u64"},
    "5883dd3b170b4f7695b9cf40916c445e":{
      "scriptId":"u65"},
    "e346e05e65554e9a822796c5042b8efe":{
      "scriptId":"u66"},
    "adabf8b60e7a446588d93cb9b9b558e1":{
      "scriptId":"u67"},
    "3c9ec90ff6c7437694e8d35fea33bfd0":{
      "scriptId":"u68"},
    "bde0c56773be4561a81d2d170819d1a3":{
      "scriptId":"u69"}}});